// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Time.proto

#include "Time.pb.h"
#include "Time.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Tempo {

static const char* Time_method_names[] = {
  "/Tempo.Time/Play",
  "/Tempo.Time/Pause",
};

std::unique_ptr< Time::Stub> Time::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Time::Stub> stub(new Time::Stub(channel, options));
  return stub;
}

Time::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Play_(Time_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Pause_(Time_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Time::Stub::Play(::grpc::ClientContext* context, const ::Tempo::Empty& request, ::Tempo::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Play_, context, request, response);
}

void Time::Stub::async::Play(::grpc::ClientContext* context, const ::Tempo::Empty* request, ::Tempo::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Play_, context, request, response, std::move(f));
}

void Time::Stub::async::Play(::grpc::ClientContext* context, const ::Tempo::Empty* request, ::Tempo::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Play_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tempo::Empty>* Time::Stub::PrepareAsyncPlayRaw(::grpc::ClientContext* context, const ::Tempo::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Play_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Tempo::Empty>* Time::Stub::AsyncPlayRaw(::grpc::ClientContext* context, const ::Tempo::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPlayRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Time::Stub::Pause(::grpc::ClientContext* context, const ::Tempo::Empty& request, ::Tempo::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Pause_, context, request, response);
}

void Time::Stub::async::Pause(::grpc::ClientContext* context, const ::Tempo::Empty* request, ::Tempo::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Pause_, context, request, response, std::move(f));
}

void Time::Stub::async::Pause(::grpc::ClientContext* context, const ::Tempo::Empty* request, ::Tempo::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Pause_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tempo::Empty>* Time::Stub::PrepareAsyncPauseRaw(::grpc::ClientContext* context, const ::Tempo::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Pause_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Tempo::Empty>* Time::Stub::AsyncPauseRaw(::grpc::ClientContext* context, const ::Tempo::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPauseRaw(context, request, cq);
  result->StartCall();
  return result;
}

Time::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Time_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Time::Service, ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Time::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Tempo::Empty* req,
             ::Tempo::Empty* resp) {
               return service->Play(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Time_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Time::Service, ::Tempo::Empty, ::Tempo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Time::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Tempo::Empty* req,
             ::Tempo::Empty* resp) {
               return service->Pause(ctx, req, resp);
             }, this)));
}

Time::Service::~Service() {
}

::grpc::Status Time::Service::Play(::grpc::ServerContext* context, const ::Tempo::Empty* request, ::Tempo::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Time::Service::Pause(::grpc::ServerContext* context, const ::Tempo::Empty* request, ::Tempo::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Tempo

