// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Status.proto

#include "Status.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Tempo {
      template <typename>
PROTOBUF_CONSTEXPR EmptyStatus::EmptyStatus(::_pbi::ConstantInitialized) {}
struct EmptyStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyStatusDefaultTypeInternal() {}
  union {
    EmptyStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyStatusDefaultTypeInternal _EmptyStatus_default_instance_;
}  // namespace Tempo
static ::_pb::Metadata file_level_metadata_Status_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Status_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Status_2eproto = nullptr;
const ::uint32_t TableStruct_Status_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Tempo::EmptyStatus, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Tempo::EmptyStatus)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Tempo::_EmptyStatus_default_instance_._instance,
};
const char descriptor_table_protodef_Status_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014Status.proto\022\005Tempo\"\r\n\013EmptyStatus2:\n\006"
    "Status\0220\n\004Ping\022\022.Tempo.EmptyStatus\032\022.Tem"
    "po.EmptyStatus\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_Status_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Status_2eproto = {
    false,
    false,
    104,
    descriptor_table_protodef_Status_2eproto,
    "Status.proto",
    &descriptor_table_Status_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Status_2eproto::offsets,
    file_level_metadata_Status_2eproto,
    file_level_enum_descriptors_Status_2eproto,
    file_level_service_descriptors_Status_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Status_2eproto_getter() {
  return &descriptor_table_Status_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Status_2eproto(&descriptor_table_Status_2eproto);
namespace Tempo {
// ===================================================================

class EmptyStatus::_Internal {
 public:
};

EmptyStatus::EmptyStatus(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:Tempo.EmptyStatus)
}
EmptyStatus::EmptyStatus(
    ::google::protobuf::Arena* arena,
    const EmptyStatus& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  EmptyStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Tempo.EmptyStatus)
}









::google::protobuf::Metadata EmptyStatus::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Status_2eproto_getter, &descriptor_table_Status_2eproto_once,
      file_level_metadata_Status_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Tempo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
