// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Status.proto

#include "Status.pb.h"
#include "Status.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Tempo {

static const char* Status_method_names[] = {
  "/Tempo.Status/Ping",
};

std::unique_ptr< Status::Stub> Status::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Status::Stub> stub(new Status::Stub(channel, options));
  return stub;
}

Status::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ping_(Status_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Status::Stub::Ping(::grpc::ClientContext* context, const ::Tempo::EmptyStatus& request, ::Tempo::EmptyStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Tempo::EmptyStatus, ::Tempo::EmptyStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void Status::Stub::async::Ping(::grpc::ClientContext* context, const ::Tempo::EmptyStatus* request, ::Tempo::EmptyStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Tempo::EmptyStatus, ::Tempo::EmptyStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void Status::Stub::async::Ping(::grpc::ClientContext* context, const ::Tempo::EmptyStatus* request, ::Tempo::EmptyStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Tempo::EmptyStatus>* Status::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::Tempo::EmptyStatus& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Tempo::EmptyStatus, ::Tempo::EmptyStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Tempo::EmptyStatus>* Status::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::Tempo::EmptyStatus& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

Status::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Status_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Status::Service, ::Tempo::EmptyStatus, ::Tempo::EmptyStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Status::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Tempo::EmptyStatus* req,
             ::Tempo::EmptyStatus* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

Status::Service::~Service() {
}

::grpc::Status Status::Service::Ping(::grpc::ServerContext* context, const ::Tempo::EmptyStatus* request, ::Tempo::EmptyStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Tempo

