# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Status.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cStatus.proto\x12\x05Tempo\"\r\n\x0b\x45mptyStatus2:\n\x06Status\x12\x30\n\x04Ping\x12\x12.Tempo.EmptyStatus\x1a\x12.Tempo.EmptyStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTYSTATUS']._serialized_start=23
  _globals['_EMPTYSTATUS']._serialized_end=36
  _globals['_STATUS']._serialized_start=38
  _globals['_STATUS']._serialized_end=96
# @@protoc_insertion_point(module_scope)
