# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Time.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nTime.proto\x12\x05Tempo\"\x07\n\x05\x45mpty2S\n\x04Time\x12$\n\x04Play\x12\x0c.Tempo.Empty\x1a\x0c.Tempo.Empty\"\x00\x12%\n\x05Pause\x12\x0c.Tempo.Empty\x1a\x0c.Tempo.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Time_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=21
  _globals['_EMPTY']._serialized_end=28
  _globals['_TIME']._serialized_start=30
  _globals['_TIME']._serialized_end=113
# @@protoc_insertion_point(module_scope)
